require("plugins.snacks")
require("plugins.tokyonight")

require("plugins.mini")

vim.schedule(function()
    require("plugins.whichkeys")
    require("plugins.noice")
    require("plugins.blink")
    require("plugins.lspconfig")
    require("plugins.treesitter")
    require("plugins.gitsigns")
    require("plugins.lualine")
    require("plugins.bufferline")
    require("plugins.trouble")
    require("plugins.conform")
    require("plugins.multicursor")
    require("plugins.mason")
    require("plugins.flash")
    require("plugins.fyler")
end)
